export const BANNED_PLATFORMS = [
  {
    id: "vinted",
    label: "Vinted",
    category: "external_platform",
    terms: ["vinted"],
    aliases: ["vint3d", "vinted marketplace"],
    fuzzy: ["vinted"],
    fragments: ["vin", "vino", "wine", "ted"],
  },
  {
    id: "vestiaire_collective",
    label: "Vestiaire Collective",
    category: "external_platform",
    terms: ["vestiaire", "vestiaire collective", "vc"],
    aliases: ["vestiairecollective"],
    fuzzy: ["vestiaire", "vestiairecollective", "collective"],
    fragments: ["vest", "iaire", "collective", "vc"],
  },
  {
    id: "grailed",
    label: "Grailed",
    category: "external_platform",
    terms: ["grailed"],
    aliases: ["grai led"],
    fuzzy: ["grailed"],
    fragments: ["grai", "led"],
  },
  {
    id: "depop",
    label: "Depop",
    category: "external_platform",
    terms: ["depop"],
    aliases: ["de pop"],
    fuzzy: ["depop"],
    fragments: ["de", "pop"],
  },
  {
    id: "ebay",
    label: "eBay",
    category: "external_platform",
    terms: ["ebay", "e bay"],
    aliases: [],
    fuzzy: ["ebay"],
    fragments: ["e", "bay"],
  },
  {
    id: "subito",
    label: "Subito",
    category: "external_platform",
    terms: ["subito", "subito.it", "subito it"],
    aliases: ["subitopuntoit"],
    fuzzy: ["subito", "subitopuntoit"],
    fragments: ["subi", "to", "punto", "it"],
  },
  {
    id: "wallapop",
    label: "Wallapop",
    category: "external_platform",
    terms: ["wallapop"],
    aliases: [],
    fuzzy: ["wallapop"],
    fragments: ["walla", "pop"],
  },
  {
    id: "poshmark",
    label: "Poshmark",
    category: "external_platform",
    terms: ["poshmark"],
    aliases: [],
    fuzzy: ["poshmark"],
    fragments: ["posh", "mark"],
  },
  {
    id: "facebook_marketplace",
    label: "Facebook Marketplace",
    category: "external_platform",
    terms: ["facebook marketplace", "marketplace facebook"],
    aliases: [],
    fuzzy: ["facebookmarketplace"],
    fragments: ["facebook", "marketplace"],
  },
];
