export const BANNED_PAYMENTS = [
  {
    id: "paypal",
    label: "PayPal",
    category: "external_payment",
    terms: ["paypal", "pay pal", "paypa1"],
    aliases: [],
    fuzzy: ["paypal"],
    fragments: ["pay", "pal"],
  },
  {
    id: "revolut",
    label: "Revolut",
    category: "external_payment",
    terms: ["revolut"],
    aliases: ["revo lut"],
    fuzzy: ["revolut"],
    fragments: ["revo", "lut"],
  },
  {
    id: "wise",
    label: "Wise",
    category: "external_payment",
    terms: ["wise"],
    aliases: [],
    fuzzy: ["wise"],
    fragments: ["wise"],
  },
  {
    id: "bonifico",
    label: "Bonifico",
    category: "external_payment",
    terms: ["bonifico", "bank transfer", "wire transfer"],
    aliases: ["boni fico"],
    fuzzy: ["bonifico", "banktransfer", "wiretransfer"],
    fragments: ["boni", "fico"],
  },
  {
    id: "iban",
    label: "IBAN",
    category: "external_payment",
    terms: ["iban"],
    aliases: [],
    fuzzy: ["iban"],
    fragments: ["iban"],
  },
  {
    id: "postepay",
    label: "Postepay",
    category: "external_payment",
    terms: ["postepay", "poste pay"],
    aliases: [],
    fuzzy: ["postepay"],
    fragments: ["poste", "pay"],
  },
  {
    id: "satispay",
    label: "Satispay",
    category: "external_payment",
    terms: ["satispay"],
    aliases: [],
    fuzzy: ["satispay"],
    fragments: ["satis", "pay"],
  },
  {
    id: "apple_pay_direct",
    label: "Apple Pay diretto",
    category: "external_payment",
    terms: ["apple pay diretto"],
    aliases: [],
    fuzzy: ["applepaydiretto"],
    fragments: ["apple", "pay"],
  },
  {
    id: "google_pay_direct",
    label: "Google Pay diretto",
    category: "external_payment",
    terms: ["google pay diretto"],
    aliases: [],
    fuzzy: ["googlepaydiretto"],
    fragments: ["google", "pay"],
  },
  {
    id: "stripe_payment_link",
    label: "Stripe payment link",
    category: "external_payment",
    terms: ["stripe payment link", "link di pagamento esterno", "checkout esterno"],
    aliases: [],
    fuzzy: ["stripepaymentlink", "checkoutesterno"],
    fragments: ["stripe", "payment", "link"],
  },
];
