export const EXTERNAL_CHANNELS = [
  {
    id: "instagram",
    label: "Instagram",
    category: "external_platform",
    terms: ["instagram", "insta", "ig", "instagram shop"],
    aliases: ["insta gram", "inst4gram"],
    fuzzy: ["instagram", "insta"],
    fragments: ["insta", "gram"],
  },
  {
    id: "telegram",
    label: "Telegram",
    category: "external_platform",
    terms: ["telegram", "tg", "tele"],
    aliases: ["tele gram", "t3legram"],
    fuzzy: ["telegram"],
    fragments: ["tele", "gram"],
  },
  {
    id: "whatsapp",
    label: "WhatsApp",
    category: "external_platform",
    terms: ["whatsapp", "whatsapp business", "wa"],
    aliases: ["whats app", "w hats app", "whats app"],
    fuzzy: ["whatsapp"],
    fragments: ["whats", "app"],
  },
  {
    id: "facebook",
    label: "Facebook",
    category: "external_platform",
    terms: ["facebook", "messenger"],
    aliases: [],
    fuzzy: ["facebook", "messenger"],
    fragments: ["face", "book", "mess", "enger"],
  },
  {
    id: "tiktok",
    label: "TikTok",
    category: "external_platform",
    terms: ["tiktok", "tik tok"],
    aliases: [],
    fuzzy: ["tiktok"],
    fragments: ["tik", "tok"],
  },
  {
    id: "discord",
    label: "Discord",
    category: "external_platform",
    terms: ["discord"],
    aliases: [],
    fuzzy: ["discord"],
    fragments: ["disc", "ord"],
  },
  {
    id: "snapchat",
    label: "Snapchat",
    category: "external_platform",
    terms: ["snapchat", "snap"],
    aliases: [],
    fuzzy: ["snapchat"],
    fragments: ["snap", "chat"],
  },
  {
    id: "email_provider",
    label: "Email provider",
    category: "contact",
    terms: ["gmail", "outlook", "hotmail"],
    aliases: [],
    fuzzy: ["gmail", "outlook", "hotmail"],
    fragments: ["g", "mail", "out", "look"],
  },
];

export const DIRECT_CONTACT_TERMS = [
  "email",
  "e-mail",
  "mail",
  "numero",
  "telefono",
  "cellulare",
  "chiamami",
  "scrivimi",
  "contattami",
  "contattaci",
  "dm",
  "direct",
  "privato",
  "mp",
  "messaggio privato",
  "handle",
  "username",
  "user",
  "profilo",
  "account",
  "nickname",
  "taggami",
  "cercami",
  "trovami",
  "stesso nickname",
  "stesso nome",
  "mio nome li",
  "mio nome lì",
  "same nickname",
];

export const CONTACT_INTRO_PHRASES = [
  "scrivimi su",
  "contattami su",
  "ti scrivo su",
  "ci sentiamo su",
  "ci vediamo su",
  "passami il contatto",
  "passami il numero",
  "ti mando il numero",
  "ti lascio la mail",
  "ti lascio il contatto",
  "mio nome li e",
  "mio nome lì è",
  "stesso nome di qui",
  "stesso nickname di qui",
  "same nickname as here",
];

export const CONTEXTUAL_SHORT_ALIASES = ["ig", "tg", "wa", "vc", "dm", "mp", "sms"];

export const CONTACT_CONTEXT_TERMS = [
  "scrivimi",
  "contattami",
  "contattaci",
  "sentiamoci",
  "cercami",
  "trovami",
  "taggami",
  "mandami",
  "passami",
  "ti lascio",
  "ti mando",
  "stesso",
  "nickname",
  "nome",
  "altrove",
  "fuori",
  "direttamente",
];
