export const OFF_PLATFORM_PHRASES = [
  { id: "offplatform_write", phrase: "scrivimi su", category: "off_platform_invitation", score: 55 },
  { id: "offplatform_contact", phrase: "contattami su", category: "off_platform_invitation", score: 55 },
  { id: "offplatform_move", phrase: "spostiamoci su", category: "off_platform_invitation", score: 55 },
  { id: "offplatform_elsewhere", phrase: "parliamo altrove", category: "off_platform_invitation", score: 50 },
  { id: "offplatform_outside", phrase: "fuori piattaforma", category: "off_platform_invitation", score: 55 },
  { id: "offplatform_better_out", phrase: "meglio fuori", category: "off_platform_invitation", score: 50 },
  { id: "offplatform_do_out", phrase: "facciamo fuori", category: "off_platform_invitation", score: 50 },
  { id: "offplatform_close_out", phrase: "chiudiamo fuori", category: "off_platform_invitation", score: 55 },
  { id: "offplatform_not_here", phrase: "non qui", category: "off_platform_invitation", score: 25 },
  { id: "offplatform_not_chat", phrase: "non in chat", category: "off_platform_invitation", score: 45 },
  { id: "offplatform_write_elsewhere", phrase: "te lo scrivo altrove", category: "off_platform_invitation", score: 50 },
  { id: "offplatform_same_nick", phrase: "stesso nickname di qui", category: "off_platform_invitation", score: 55 },
  { id: "payment_outside", phrase: "ti pago fuori", category: "payment_bypass", score: 55 },
  { id: "payment_direct", phrase: "pagamento diretto", category: "payment_bypass", score: 50 },
  { id: "payment_outside_site", phrase: "fuori dal sito", category: "payment_bypass", score: 55 },
  { id: "payment_without_fee", phrase: "senza commissioni", category: "payment_bypass", score: 55 },
  { id: "payment_avoid_fees", phrase: "evitiamo le fee", category: "payment_bypass", score: 55 },
  { id: "payment_avoid_commissioni", phrase: "evitiamo la commissione", category: "payment_bypass", score: 55 },
  { id: "payment_no_checkout", phrase: "senza checkout", category: "payment_bypass", score: 55 },
  { id: "payment_dont_checkout", phrase: "non usare checkout", category: "payment_bypass", score: 55 },
  { id: "payment_save_money", phrase: "cosi risparmiamo", category: "payment_bypass", score: 50 },
  { id: "payment_agree_outside", phrase: "ci accordiamo fuori", category: "payment_bypass", score: 55 },
];
