export const SEMANTIC_HINTS = [
  {
    id: "photos_social",
    category: "external_platform",
    score: 30,
    phrases: ["social delle foto", "app delle foto", "dove ci sono le storie", "logo della macchina fotografica"],
    target: "instagram",
  },
  {
    id: "green_messages_app",
    category: "external_platform",
    score: 32,
    phrases: ["app verde", "quello verde per i messaggi", "quella verde per i messaggi"],
    target: "whatsapp",
  },
  {
    id: "green_generic",
    category: "external_platform",
    score: 28,
    phrases: ["quello verde", "quella verde"],
    target: "whatsapp",
  },
  {
    id: "paper_plane_app",
    category: "external_platform",
    score: 32,
    phrases: ["app con l aeroplanino", "quella con l aeroplanino", "quello con il paper plane", "paper plane"],
    target: "telegram",
  },
  {
    id: "platform_with_v",
    category: "external_platform",
    score: 28,
    phrases: ["quella con la v", "piattaforma famosa con la v", "marketplace usato famoso", "app viola per comprare vestiti usati"],
    target: "vinted",
  },
  {
    id: "same_nickname_external",
    category: "contact",
    score: 40,
    phrases: ["stesso nome di qui", "stesso nickname di qui", "mio nome li e", "mio nome lì è", "il mio nome e uguale altrove", "same nickname as here"],
    target: "external_profile",
  },
  {
    id: "cant_say_here",
    category: "evasion",
    score: 25,
    phrases: ["non posso scriverlo qui", "non lo posso scrivere qui", "non te lo posso dire qui", "te lo faccio intuire", "te lo faccio capire", "non posso dirlo qui"],
    target: "coded_hint",
  },
  {
    id: "mutual_understanding",
    category: "evasion",
    score: 26,
    phrases: ["hai capito", "ci siamo capiti", "basta interpretare", "e ovvio", "è ovvio"],
    target: "coded_hint",
  },
  {
    id: "outside_is_better",
    category: "off_platform_invitation",
    score: 30,
    phrases: ["fuori da qui e meglio", "fuori da qui è meglio", "meglio altrove", "meglio fuori di qui"],
    target: "outside_platform",
  },
];
